version: '3'
services:
  web:
    build: ./blogpost/web
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
  db:
    build: ./blogpost/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped 
    environment:
      MYSQL_ROOT_PASSWORD: example #do not change, it is used by the checker to verify service availability
      MYSQL_DATABASE: blog
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: blogpassword
    ports:
      - "3306:3306"
  buycart:
    image: buycart
    build:
      context: ./buycart
      dockerfile: Dockerfile
      args:
        admin: admin
    ports:
      - "5000:5000"
